- name: Make a file
  hosts: "{{ target_hosts | default('all') }}"

  tasks:
    - name: Create a file
      copy:
        content: test
        dest: /tmp/test.txt
        
    - name: Add content
      lineinfile:
        path: /tmp/test.txt
        line: "Hola creado por Ansible"
