---
- name: Install packages
  hosts: all
  become: true
  tasks:
  
  - name: Install a package
    yum:
      name: "{{ package }}"
      state: absent
      
  - name: Upgrade S.O.
    yum:
      state: latest
      name: '*'
      exclude: kernel*
      
